#
# Used for running MNIST example with an asynchronous steady-state EA
#
# gremlin.py bygen-dist.yml async.yml
#
algorithm: async
async: # parameters for asynchronous steady-state EA
  init_pop_size: ${pop_size} # default to pop size, but can be set to the number of dask workers
  max_births: 100
  ind_file: inds.csv # optional file for writing individuals as they are evaluated
  ind_file_probe: probe.log_ind # optional functor or function for writing ind_file
pipeline:
  - ops.random_selection # randomly select from pool of prospective parents
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - ops.pool(size=1) # for ASEA needs to be one since we're asynchronous assigning a single offspring to a worker to be evaluated
