# Gremlin config file for MNIST example
#
# Usage:
#     $ gremlin.py config.yml
pop_size: 5
max_generations: 4
problem: problem.MNISTProblem
representation: representation.MNISTRepresentation
pop_file: pop.csv # where we will write out each generation in CSV format
imports:
  - probe
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - ops.evaluate
  - probe.IndividualProbeCSV('inds.csv') # our own probe to see every single created offspring
  - ops.pool(size=${pop_size})
