# Gremlin config file for MNIST example
#
# Usage:
#     $ gremlin.py config.yml
pop_size: 5
pop_file: pop.csv # where we will write out each generation in CSV format
max_generations: 4
problem: problem.MNISTProblem
representation: representation.MNISTRepresentation
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.genome_bounds)
  - ops.evaluate
  - ops.pool(size=pop_size)
