# Gremlin config file for MNIST example
#
# Usage:
#     $ gremlin.py config.yml
pop_size: 10
max_generations: 2
problem: problem.MNISTProblem
representation: representation.MNISTRepresentation
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.genome_bounds)
  - ops.evaluate
  - ops.pool(size=pop_size)
