# Gremlin config file for MNIST example
#
# config_debug.yml just overrides the pop_size, max_generations, and k_elites
#
# Essentially this is for running with a very small population just to step
# through the debugger, and also demonstrates how consecutive YAML config files
# override command-line predecessors.
#
# Usage:
#     $ gremlin.py config.yml config_debug.yml
pop_size: 1
bygen: # parameters that only make sense for a by-generation EA
  max_generations: 1
  k_elites: 0
