# Gremlin config file for MNIST example
#
# Usage:
#     $ gremlin.py config.yml
pop_size: 7
max_generations: 5
k_elites: 2 # optional parameter for specifying the number (k) elites we keep per generation
problem: problem.MNISTProblem()
representation: representation.MNISTRepresentation()
pop_file: pop.csv # where we will write out each generation in CSV format
imports:
  - probe # need to import our probe.py so that LEAP sees our probe pipeline operator
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - ops.evaluate
  - probe.IndividualProbeCSV('inds.csv') # our own probe to see every single created offspring
  - ops.pool(size=${pop_size})
